---
title: संपर्क किए गए कमरे
hero_image: छवियों / banner.png
theme: लाल
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, डिजाइन -1, प्रोग्रामिंग -0, फिजिकल-कम्प -0, निर्माण -0, समुदाय -0
description: एक साथ जुड़े कई 'rooms' के साथ वेब प्रोजेक्ट बनाएँ।
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: प्रॉजेक्ट
hardware: ''
software: htmp-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: समान प्रोजेक्ट में अन्य वेब पेज से लिंक करना
  - 
    title: 'चुनौती: अन्य लिंक जोड़ें'
  - 
    title: अन्य कमरा जोड़ें
  - 
    title: 'चुनौती: गेम्स रूम को स्टाइल दें और लिंक करें'
  - 
    title: दरवाज़ों की तरह दिखाई देने वाले लिंक बनाएँ
  - 
    title: 'चुनौती: और दरवाज़े जोड़ें!'
  - 
    title: पृष्ठभूमि छवि जोड़ना
  - 
    title: 'चुनौती: गेम्स रूम में वॉलपेपर जोड़ें'
  - 
    title: 'चुनौती: इसे अपना बनाएँ!'
