---
title: Salas Ligadas
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Criar um projeto web com diversas "salas" ligadas entre si.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introdução
  completion: engaged
- title: Ligar a outra página web no mesmo projeto
- title: 'Desafio: Acrescenta outro link'
- title: Acrescentar outra sala
- title: 'Desafio: Estiliza e liga a Sala de Jogos'
- title: Faz com que os links se pareçam com portas
- title: 'Desafio: Adiciona mais portas!'
- title: Acrescenta uma imagem de fundo
- title: 'Desafio: Acrescenta uma imagem de fundo à Sala de Jogos'
  completion: internal
- title: 'Desafio: Personaliza-o!'
