---
title: Quartos Ligados
hero_image: images/banner.png
theme: vermelho
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Criar um projeto web com diversos "quartos" ligados entre si.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projetos
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Ligar a outra página web no mesmo projeto
  - 
    title: 'Desafio: Acrescenta outro link'
  - 
    title: Acrescentar outro quarto
  - 
    title: 'Desafio: Caracteriza e liga os Quartos de Jogo'
  - 
    title: Faz com que os links se pareçam com portas
  - 
    title: 'Desafio: adiciona mais portas!'
  - 
    title: Acrescenta uma imagem de fundo
  - 
    title: 'Desafio: Acrescenta uma imagem de fundo aos Quartos de Jogo'
  - 
    title: 'Desafio: Personaliza-o!'
