---
title: Salas Enlazadas
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Crea un nuevo proyecto web con varias “habitaciones” unidas.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Crear un enlace a otra página web en el mismo proyecto
  - 
    title: 'Desafío: Añadir otro enlace'
  - 
    title: Añadir otra sala
  - 
    title: 'Desafío: Dar estilo y enlazar la Sala de juegos'
  - 
    title: Haz que los enlaces parezcan puertas
  - 
    title: 'Desafío: ¡Añadir más puertas!'
  - 
    title: Añadir una imagen de fondo
  - 
    title: 'Desafío: Empapelar la Sala de juegos'
  - 
    title: 'Desafío: ¡Hazlo tuyo!'
