---
title: Verknüpfte Zimmer
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Erstelle ein Projekt mit mehreren "Zimmern", die miteinander verknüpft sind.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Stelle eine Verknüpfung zu einer anderen Webseite im gleichen Projekt her
  - 
    title: 'Herausforderung: Füge eine weitere Verknüpfung hinzu'
  - 
    title: Füge ein weiteres Zimmer hinzu
  - 
    title: 'Herausforderung: Gestalte und verknüpfe das Spielzimmer'
  - 
    title: Lasse die Verknüpfungen wie Türen aussehen
  - 
    title: 'Herausforderung: Füge weitere Türen hinzu!'
  - 
    title: Ein Hintergrundbild hinzufügen
  - 
    title: 'Herausforderung: Füge eine Tapete zum Spielzimmer hinzu'
  - 
    title: 'Herausforderung: Mache es zu Deinem!'
