---
title: Cômodos Interligados
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Crie um projeto web com vários "cômodos" interligados.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introdução
  completion: engaged
- title: Vinculando a outra página da Web no mesmo projeto
- title: 'Desafio: adicione outro link'
- title: Adicione outra sala
- title: 'Desafio: desenhe e interligue a sala de jogos'
- title: Faça com que os links pareçam portas
- title: 'Desafio: adicione mais portas!'
- title: Adicionando imagem de fundo
- title: 'Desafio: adicione papel de parede à Sala de Jogos'
  completion: internal
- title: 'Desafio: faça do seu jeito!'
