---
title: Cômodos Interligados
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Neste projeto, você vai criar um conjunto de cômodos interligados no qual cada cômodo é uma página web diferente que pode ser decorada usando HTML.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Vinculando a outra página da Web no mesmo projeto
  - 
    title: 'Desafio: Adicione outro link'
  - 
    title: Adicione outra sala
  - 
    title: 'Desafio: Decore e interligue a sala de jogos'
  - 
    title: Faça os links parecer como portas
  - 
    title: 'Desafio: adicione mais portas!'
  - 
    title: Adicionando uma imagem de fundo
  - 
    title: 'Desafio: Adicione papel de parede à Sala de Jogos'
  - 
    title: 'Desafio: Personalize!'
