---
title: Cômodos Interligados
hero_image: imagens/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Neste projeto, você vai criar um conjunto de cômodos interligados no qual cada cômodo é uma página web diferente que pode ser decorada usando HTML.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Cômodos Interligados
  - 
    title: Linking to another web page in the same project
  - 
    title: 'Challenge: Add another link'
  - 
    title: Add another room
  - 
    title: 'Challenge: Style and link the Games Room'
  - 
    title: Make the links look like doors
  - 
    title: 'Challenge: Add more doors!'
  - 
    title: Adding a background image
  - 
    title: 'Challenge: Add wallpaper to the Games Room'
  - 
    title: 'Challenge: Make it yours!'
