---
title: Habitaciones enlazadas
hero_image: images/banner.png
theme: rojo
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Crea un proyecto web con varias 'habitaciones' enlazadas.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: proyectos
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Crea un enlace a otra página web en el mismo proyecto
  - 
    title: 'Desafío: Añade otro enlace'
  - 
    title: Añade otra sala
  - 
    title: 'Desafío: Dale estilo y enlaza la Sala de juegos'
  - 
    title: Hacer que los enlaces se vean como puertas
  - 
    title: 'Desafío: ¡Añade más puertas!'
  - 
    title: Añade una imagen de fondo
  - 
    title: 'Desafío: Añadir fondo de pantalla a la Sala de Juegos'
  - 
    title: 'Desafío: ¡Hazlo tuyo!'
