---
title: Pokoje
hero_image: images / banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, projekt-1, programowanie-0, obliczenia-fizyczne-0, produkcja-0, społeczność-0
description: Zbuduj kilka połączonych pokojów, z których każdy jest osobną stroną internetową.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projekty
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Linkowanie do innej strony w tym samym projekcie
  - 
    title: 'Wyzwanie: Dodaj kolejny link'
  - 
    title: Dodaj kolejny pokój
  - 
    title: 'Wyzwanie: Ostyluj i podlinkuj pokój zabaw'
  - 
    title: Linki, które wyglądają jak drzwi
  - 
    title: 'Wyzwanie: Jeszcze więcej drzwi!'
  - 
    title: Dodawanie tła
  - 
    title: 'Wyzwanie: Dodaj tapetę do Pokoju Zabaw'
  - 
    title: 'Wyzwanie: Zrób po swojemu!'
