---
title: Povezane prostorije
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Izradi veb-projekat sa nekoliko međusobno povezanih 'prostorija'.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
  completion: engaged
- title: Povezivanje sa drugom veb-stranicom u istom projektu
- title: 'Izazov: Dodaj još jedan link'
- title: Dodaj još jednu salu
- title: 'Izazov: Stilizuj i poveži Salu za igre'
- title: Napravi da linkovi izgledaju kao vrata
- title: 'Izazov: Dodaj više vrata!'
- title: Dodavanje pozadinske slike
- title: 'Izazov: Dodaj tapet Sali za igre'
  completion: internal
- title: 'Izazov: Uradi to na svoj način!'
