---
title: Stanze collegate
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Crea un progetto Web con diverse 'stanze' collegate tra loro.
original_url: https://codeclubprojects.org/en-GB/webdev/linked-rooms
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduzione
- title: "Collegamento a un’altra pagina Web dello stesso progetto"
- title: 'Sfida: Aggiungi un altro link'
- title: "Aggiungi un’altra stanza"
- title: 'Sfida: Attribuisci degli stili e collega la Games Room (Stanza dei giochi)'
- title: Trasformiamo i link in porte
- title: 'Sfida: Aggiungi altre porte!'
- title: "Aggiunta di un’immagine di sfondo"
- title: 'Sfida: Aggiungi la carta da parati alla Games Room (Stanza dei giochi)'
- title: 'Sfida: Personalizzala!'